<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8" />
  <title>Protected Mode. Not all exceptions are catched... - Forums - ASM Community</title>
  <link rel="stylesheet" type="text/css" href="../../../style.css" />
  <link rel="canonical" href="../?id=30969" />
     </head>
 <body>
  <div id="header">
   <h1><a href="../../../">ASM Community</a></h1>
  </div>
  <div id="content">
   <p class="breadcrumbs"><a href="../../../">Home</a> &raquo; <a href="../../">Forums</a> &raquo; <a href="../../board/?id=34">OS Development</a> &raquo; <a href="../?id=30969">Protected Mode. Not all exceptions are catched...</a></p>
   <div class="post" id="post-216553">
    <div class="subject"><a href="#post-216553">Protected Mode. Not all exceptions are catched...</a></div>
    <div class="body">Hey, <br />Using tasm and dosbox I have done (right) code to move from real to protected mode and from protected mode to real and all is working fine (tested!). There is a small problem with interrupts/exceptions, becouse it seems like all of them are not catched, what is kinda strange.<br /><br />My idt:<br /><pre><code>&nbsp; idt label word<br />&nbsp; &nbsp; exception0		pulapka &lt;exception_0&gt;<br />&nbsp; &nbsp; exception_def	pulapka &lt;exception_default&gt;<br />&nbsp; &nbsp; pulapka 30 DUP (&lt;exception_default&gt;)<br />&nbsp; idt_size = $ - idt</code></pre><br /><br />pulapka is a structure:<br /><pre><code>pulapka struc<br />&nbsp; offs_1 	dw 0<br />&nbsp; sel 		dw 16<br />&nbsp; rsrv		db 0<br />&nbsp; attr 		db 8fh<br />&nbsp; offs_h 	dw 0<br />pulapka ends</code></pre><br /><br />exception_0 and exception_default are procedures that serve interrupts<br /><br />So as far as you can notice if i would DIV by 0 it would call exception_0 procedure<br />If any other exception it would call exception_default procedure. And it mostly like that...<br /><br />If i run this code in protected mode:<br /><pre><code>mov ax, 6<br />mov dx, 0<br />div dx</code></pre><br />I get result of exception_0 procedure - printed text at screen - OK<br /><br />If i run this code in protected mode:<br /><pre><code>mov ax, 10<br />mov fs, ax<br />int 20h</code></pre><br />I get result of exception_default procedure - different text printed at scrren, with different position - OK<br /><br />So it seems interrupt&#039;s are served properly, but... if i run in pm mode this:<br /><br /><pre><code>mov ax, ds:</code></pre><br /><br />where data_size is size of data segment (ds). I get no exception... i have moved outside segment border so why there is no exception ?!<br /><br />Reading program segment isn&#039;t also throwing an exepction (98h attribute for this CS descriptior):<br /><pre><code>mov al, cs:[0]</code></pre><br /><br /><br />Why ? What may be wrong ?</div>
    <div class="meta">Posted on 2013-05-06 14:43:07 by hElllk</div>
   </div>
  </div>
 </body>
</html>